const data = [
  {
    "regionId": 137,
    "regionCode": "Ru0GQBoH",
    "regionName": "0907",
    "buildingCount": 1,
    "description": "测试RGBD和RGB建图",
    "isRelated": false,
    "relatedProjectIds": [],
    "relatedProject": null,
    "createdProjectId": 32,
    "createdProjectName": "建图项目",
    "createdEmail": "lvjiyuan@sensetime.com",
    "createdBy": "lvjiyuan_1657175105",
    "createdTime": 1662517767000,
    "updatedTime": 1662517767000,
    "gpsBoundary": "",
    "buildings": [
      {
        "regionId": 137,
        "buildingId": 211,
        "buildingCode": "sgjww0Ez",
        "buildingName": "DefaultSite",
        "buildingTypeName": "Business",
        "blockCount": 14,
        "description": "",
        "createdTime": 1662517767000,
        "updatedTime": 1662517767000,
        "gpsBoundary": "",
        "blocks": [
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 531,
            "blockCode": "EIMaJvHs",
            "blockName": "FFFFFFFF",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F1",
            "description": "",
            "createdTime": 1667819598000,
            "updatedTime": 1669256899000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 530,
            "blockCode": "5wn0lV9G",
            "blockName": "BBB",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F22",
            "description": "",
            "createdTime": 1667819557000,
            "updatedTime": 1668514135000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 529,
            "blockCode": "Ddbt0Bnu",
            "blockName": "test",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F3",
            "description": "",
            "createdTime": 1667814361000,
            "updatedTime": 1668569543000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 528,
            "blockCode": "DgPuY5mw",
            "blockName": "ffff",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1667812192000,
            "updatedTime": 1667812192000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 527,
            "blockCode": "Q0Gx0zMn",
            "blockName": "ttt",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "f1",
            "description": "",
            "createdTime": 1667812049000,
            "updatedTime": 1668670833000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 458,
            "blockCode": "LI35FN6i",
            "blockName": "翠微百货12",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1665488284000,
            "updatedTime": 1667377487000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 455,
            "blockCode": "MU4VZtVV",
            "blockName": "20M",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F20",
            "description": "",
            "createdTime": 1664417093000,
            "updatedTime": 1664417093000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 447,
            "blockCode": "3YcV6rdp",
            "blockName": "测试20M",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F8",
            "description": "",
            "createdTime": 1663728409000,
            "updatedTime": 1663751704000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 445,
            "blockCode": "fM1gAF06",
            "blockName": "测试rgbd",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F12",
            "description": "",
            "createdTime": 1663569876000,
            "updatedTime": 1663667303000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 425,
            "blockCode": "kOr69Hsg",
            "blockName": "RTK",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1662636754000,
            "updatedTime": 1669203833000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 424,
            "blockCode": "UBdHagvy",
            "blockName": "翠微百货",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1662627774000,
            "updatedTime": 1662627774000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 420,
            "blockCode": "xUNNgPVo",
            "blockName": "10A8Finsta360",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "A8",
            "description": "10A8Finsta360是RGB的建图",
            "createdTime": 1662517817000,
            "updatedTime": 1662517817000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 419,
            "blockCode": "V0c0nmfy",
            "blockName": "12A22F",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F22",
            "description": "12A22F的是RGBD建图",
            "createdTime": 1662517801000,
            "updatedTime": 1662517801000
          },
          {
            "regionId": 137,
            "buildingId": 211,
            "blockId": 418,
            "blockCode": "5CX84Z64",
            "blockName": "F1",
            "areaSize": null,
            "gpsBoundary": null,
            "floorNum": "F1",
            "description": "",
            "createdTime": 1662517767000,
            "updatedTime": 1662517767000
          }
        ]
      },
      {
        "regionId": 119,
        "buildingId": 180,
        "buildingCode": "yLBSEY22",
        "buildingName": "建筑1",
        "buildingTypeName": "Business",
        "blockCount": 14,
        "description": "",
        "createdTime": 1658214197000,
        "updatedTime": 1658214197000,
        "gpsBoundary": "",
        "blocks": [
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 367,
            "blockCode": "0NIMfWPr",
            "blockName": "测试蓝牙0816",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F17",
            "description": "",
            "createdTime": 1660616360000,
            "updatedTime": 1660616360000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 365,
            "blockCode": "yJMJNahW",
            "blockName": "测试rgbd建图",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F15",
            "description": "",
            "createdTime": 1660268968000,
            "updatedTime": 1660268968000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 364,
            "blockCode": "l5Kp5bF9",
            "blockName": "0812",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F13",
            "description": "",
            "createdTime": 1660188658000,
            "updatedTime": 1660188658000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 362,
            "blockCode": "sUNywQKj",
            "blockName": "0811",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F11",
            "description": "",
            "createdTime": 1660118023000,
            "updatedTime": 1660118023000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 360,
            "blockCode": "ZXnFvrt2",
            "blockName": "0810",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F10",
            "description": "",
            "createdTime": 1660095205000,
            "updatedTime": 1660095205000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 359,
            "blockCode": "dMXnnyQg",
            "blockName": "testqrcode",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F8",
            "description": "",
            "createdTime": 1660033571000,
            "updatedTime": 1660033571000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 349,
            "blockCode": "Ci5C45nh",
            "blockName": "RGBD",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1659491450000,
            "updatedTime": 1659491450000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 348,
            "blockCode": "kgVvdhvI",
            "blockName": "GOGOGO",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F4",
            "description": "",
            "createdTime": 1659357005000,
            "updatedTime": 1659357005000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 342,
            "blockCode": "ucyILJJj",
            "blockName": "辅助定位",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F6",
            "description": "",
            "createdTime": 1658302124000,
            "updatedTime": 1668418819000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 341,
            "blockCode": "MzMFzfKH",
            "blockName": "点云测距",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F5",
            "description": "",
            "createdTime": 1658301037000,
            "updatedTime": 1658301037000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 340,
            "blockCode": "JcvwYX32",
            "blockName": "F4",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F4",
            "description": "",
            "createdTime": 1658298111000,
            "updatedTime": 1658298111000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 339,
            "blockCode": "Fm3xfzPA",
            "blockName": "F3测试",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F3",
            "description": "",
            "createdTime": 1658282918000,
            "updatedTime": 1658282918000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 338,
            "blockCode": "97VGUODo",
            "blockName": "F2cad",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1658229269000,
            "updatedTime": 1658229269000
          },
          {
            "regionId": 119,
            "buildingId": 180,
            "blockId": 337,
            "blockCode": "HUYpPVYc",
            "blockName": "F1",
            "areaSize": null,
            "gpsBoundary": null,
            "floorNum": "F1",
            "description": "",
            "createdTime": 1658214197000,
            "updatedTime": 1658214197000
          }
        ]
      }
    ]
  },
  {
    "regionId": 134,
    "regionCode": "oDvF3PgR",
    "regionName": "0901",
    "buildingCount": 1,
    "description": "",
    "isRelated": false,
    "relatedProjectIds": [],
    "relatedProject": null,
    "createdProjectId": 32,
    "createdProjectName": "建图项目",
    "createdEmail": "lijie6@sensetime.com",
    "createdBy": "lijie6_1657180401",
    "createdTime": 1662022068000,
    "updatedTime": 1662022068000,
    "gpsBoundary": "",
    "buildings": [
      {
        "regionId": 134,
        "buildingId": 207,
        "buildingCode": "uu3fzFyU",
        "buildingName": "建筑2",
        "buildingTypeName": "Business",
        "blockCount": 7,
        "description": "",
        "createdTime": 1662022068000,
        "updatedTime": 1662022068000,
        "gpsBoundary": "",
        "blocks": [
          {
            "regionId": 134,
            "buildingId": 207,
            "blockId": 443,
            "blockCode": "AXzaOkZo",
            "blockName": "测试新增20m",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F11",
            "description": "",
            "createdTime": 1663567798000,
            "updatedTime": 1663567798000
          },
          {
            "regionId": 134,
            "buildingId": 207,
            "blockId": 415,
            "blockCode": "xg6hAFqv",
            "blockName": "测试增量更新",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F9",
            "description": "",
            "createdTime": 1662458457000,
            "updatedTime": 1662458457000
          },
          {
            "regionId": 134,
            "buildingId": 207,
            "blockId": 412,
            "blockCode": "tWznCDtt",
            "blockName": "增量更新测试软链接",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1662348926000,
            "updatedTime": 1662348926000
          },
          {
            "regionId": 134,
            "buildingId": 207,
            "blockId": 411,
            "blockCode": "AR8VIYBX",
            "blockName": "翠微百货",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F1",
            "description": "",
            "createdTime": 1662114630000,
            "updatedTime": 1662114630000
          },
          {
            "regionId": 134,
            "buildingId": 207,
            "blockId": 406,
            "blockCode": "w3Zm3Xec",
            "blockName": "测试相机标定",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F3",
            "description": "",
            "createdTime": 1662024351000,
            "updatedTime": 1662024351000
          },
          {
            "regionId": 134,
            "buildingId": 207,
            "blockId": 405,
            "blockCode": "Sz3ivikP",
            "blockName": "测试删除资源",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1662024136000,
            "updatedTime": 1662024136000
          },
          {
            "regionId": 134,
            "buildingId": 207,
            "blockId": 404,
            "blockCode": "pCVFJmws",
            "blockName": "F1",
            "areaSize": null,
            "gpsBoundary": null,
            "floorNum": "F1",
            "description": "",
            "createdTime": 1662022069000,
            "updatedTime": 1662022069000
          }
        ]
      }
    ]
  },
  {
    "regionId": 124,
    "regionCode": "oJXfrCmF",
    "regionName": "0822李杰测试",
    "buildingCount": 1,
    "description": "",
    "isRelated": false,
    "relatedProjectIds": [],
    "relatedProject": null,
    "createdProjectId": 32,
    "createdProjectName": "建图项目",
    "createdEmail": "lijie6@sensetime.com",
    "createdBy": "lijie6_1657180401",
    "createdTime": 1661149591000,
    "updatedTime": 1661149591000,
    "gpsBoundary": "",
    "buildings": [
      {
        "regionId": 124,
        "buildingId": 191,
        "buildingCode": "8PMmdZc5",
        "buildingName": "建筑3",
        "buildingTypeName": "Business",
        "blockCount": 8,
        "description": "",
        "createdTime": 1661149591000,
        "updatedTime": 1661149591000,
        "gpsBoundary": "",
        "blocks": [
          {
            "regionId": 124,
            "buildingId": 191,
            "blockId": 579,
            "blockCode": "Ur8u6Q4j",
            "blockName": "测试部署2",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F18",
            "description": "",
            "createdTime": 1668656359000,
            "updatedTime": 1668656359000
          },
          {
            "regionId": 124,
            "buildingId": 191,
            "blockId": 578,
            "blockCode": "9iyO7FVd",
            "blockName": "测试部署",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F17",
            "description": "",
            "createdTime": 1668656304000,
            "updatedTime": 1668656304000
          },
          {
            "regionId": 124,
            "buildingId": 191,
            "blockId": 441,
            "blockCode": "VgqCpdYC",
            "blockName": "测试marker3",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F7",
            "description": "",
            "createdTime": 1663300319000,
            "updatedTime": 1663300319000
          },
          {
            "regionId": 124,
            "buildingId": 191,
            "blockId": 440,
            "blockCode": "LZqtBdp0",
            "blockName": "测试marker",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F6",
            "description": "",
            "createdTime": 1663300038000,
            "updatedTime": 1663300038000
          },
          {
            "regionId": 124,
            "buildingId": 191,
            "blockId": 382,
            "blockCode": "NngmLuNg",
            "blockName": "测试员",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1661402810000,
            "updatedTime": 1661402810000
          },
          {
            "regionId": 124,
            "buildingId": 191,
            "blockId": 373,
            "blockCode": "e0Urc7hJ",
            "blockName": "手机增量更新",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1661253516000,
            "updatedTime": 1661253516000
          },
          {
            "regionId": 124,
            "buildingId": 191,
            "blockId": 371,
            "blockCode": "dnqTS31v",
            "blockName": "测试cad",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1661222493000,
            "updatedTime": 1661222493000
          },
          {
            "regionId": 124,
            "buildingId": 191,
            "blockId": 370,
            "blockCode": "G8HkJMKc",
            "blockName": "F1",
            "areaSize": null,
            "gpsBoundary": null,
            "floorNum": "F1",
            "description": "",
            "createdTime": 1661149592000,
            "updatedTime": 1662545097000
          }
        ]
      }
    ]
  },
  {
    "regionId": 123,
    "regionCode": "NIif4PLz",
    "regionName": "0809",
    "buildingCount": 1,
    "description": "",
    "isRelated": false,
    "relatedProjectIds": [],
    "relatedProject": null,
    "createdProjectId": 32,
    "createdProjectName": "建图项目",
    "createdEmail": "lvjiyuan@sensetime.com",
    "createdBy": "lvjiyuan_1657175105",
    "createdTime": 1660030309000,
    "updatedTime": 1660030309000,
    "gpsBoundary": "",
    "buildings": [
      {
        "regionId": 123,
        "buildingId": 190,
        "buildingCode": "Uib9hrAO",
        "buildingName": "建筑4",
        "buildingTypeName": "Business",
        "blockCount": 8,
        "description": "",
        "createdTime": 1660030309000,
        "updatedTime": 1660030309000,
        "gpsBoundary": "",
        "blocks": [
          {
            "regionId": 123,
            "buildingId": 190,
            "blockId": 444,
            "blockCode": "871puqiB",
            "blockName": "测试rgbd",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F12",
            "description": "",
            "createdTime": 1663569850000,
            "updatedTime": 1663569850000
          },
          {
            "regionId": 123,
            "buildingId": 190,
            "blockId": 384,
            "blockCode": "IJtfNU9n",
            "blockName": "测试中断",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1661409607000,
            "updatedTime": 1661409607000
          },
          {
            "regionId": 123,
            "buildingId": 190,
            "blockId": 374,
            "blockCode": "XOVEj9Cr",
            "blockName": "手机增量更新",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1661253608000,
            "updatedTime": 1661253608000
          },
          {
            "regionId": 123,
            "buildingId": 190,
            "blockId": 369,
            "blockCode": "hVMk3bXK",
            "blockName": "MVS测试",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1660807538000,
            "updatedTime": 1660807538000
          },
          {
            "regionId": 123,
            "buildingId": 190,
            "blockId": 368,
            "blockCode": "G9qCM9GX",
            "blockName": "天人大厦",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F29",
            "description": "",
            "createdTime": 1660788694000,
            "updatedTime": 1660788694000
          },
          {
            "regionId": 123,
            "buildingId": 190,
            "blockId": 363,
            "blockCode": "Uevm93lg",
            "blockName": "测试OSGB耗时",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F2",
            "description": "",
            "createdTime": 1660188558000,
            "updatedTime": 1660188558000
          },
          {
            "regionId": 123,
            "buildingId": 190,
            "blockId": 361,
            "blockCode": "CFQz2Ufu",
            "blockName": "RGBD",
            "areaSize": null,
            "gpsBoundary": "",
            "floorNum": "F13",
            "description": "",
            "createdTime": 1660102283000,
            "updatedTime": 1660102283000
          },
          {
            "regionId": 123,
            "buildingId": 190,
            "blockId": 358,
            "blockCode": "nFXANLKb",
            "blockName": "F1",
            "areaSize": null,
            "gpsBoundary": null,
            "floorNum": "F1",
            "description": "",
            "createdTime": 1660030310000,
            "updatedTime": 1660030310000
          }
        ]
      }
    ]
  },
  {
    "regionId": 119,
    "regionCode": "ta8TAKhD",
    "regionName": "0720李杰测试",
    "buildingCount": 1,
    "description": "",
    "isRelated": false,
    "relatedProjectIds": [],
    "relatedProject": null,
    "createdProjectId": 32,
    "createdProjectName": "建图项目",
    "createdEmail": "lijie6@sensetime.com",
    "createdBy": "lijie6_1657180401",
    "createdTime": 1658214197000,
    "updatedTime": 1658214197000,
    "gpsBoundary": "",
    "buildings": []
  }
]

export default data